language: ruby
rvm:
- 2.1
before_install:
    gem install jekyll jekyll-paginate html-proofer -N;
    sudo pip install Pygments

script: jekyll build && htmlproof --href-ignore "#" ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
