language: ruby
rvm:
- 2.1
sudo: required

before_install:
  - sudo pip install Pygments
  - gem install jekyll jekyll-paginate html-proofer -N

script: jekyll build && htmlproof --href-ignore "#" ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
