# Site settings
title: AudioKit
email: audiokit@audiokit.io
description: > #
  AudioKit, an open-source audio synthesis, processing, and analysis platform.
url: "http://audiokit.io" # the base hostname & protocol for your site
port: 4444
permalink: /blog/:year/:month/:day/:title/
twitter_username:
github_username:  AudioKit

# Build settings
markdown: kramdown
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:
  gallery:
    output: true
    permalink: /gallery/:path/
