# Site settings
title: Audio Kit
email: audiokit@hearforyourself.com
description: > #
  Audio Kit, an open-source audio synthesis, processing, and analysis platform.
url: "http://audiokit.io" # the base hostname & protocol for your site
twitter_username:
github_username:  AudioKit

# Build settings
markdown: kramdown
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
